---
version: '2.1'
services:
  redis:
    image: redis:3.2.11-alpine
    ports:
      - "6379:6379"
  backend:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
    links:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  # if we want nginx to serve the page
  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - backend
